server   = "tcp:bngllzl65ieu5mb2tukte3jkva-4f53yvqio6sefpnrrcqojcc4fq.datawarehouse.fabric.microsoft.com,1433"
database = "LH_SILVER"
tenant_id = "e5b54c0b-ea7e-4e09-b03a-9d15326d2aa8"
auth_mode = "browser"